# Generated by Django 5.1.4 on 2024-12-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo_anime', models.CharField(max_length=50)),
                ('episodios', models.IntegerField()),
                ('url', models.URLField()),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('Emisión', 'En emisión'), ('Finalizado', 'Finalizado'), ('Pendiente', 'Pendiente')], max_length=50)),
                ('generos', models.CharField(max_length=255)),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
